# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 05:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_author', models.CharField(max_length=250)),
                ('news_title', models.CharField(max_length=400)),
                ('news_contens', models.TextField()),
                ('news_url', models.URLField(max_length=300)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('news_type', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('category', models.ManyToManyField(to='portfolio.Category')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=400)),
                ('post_title', models.CharField(max_length=400)),
                ('post_photo', models.ImageField(blank=True, upload_to='posts')),
                ('post_content', models.TextField()),
                ('post_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('post_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('post_type', models.CharField(max_length=200)),
                ('comment_count', models.IntegerField(default=0)),
                ('post_code', models.TextField(default='')),
                ('category', models.ManyToManyField(to='portfolio.Category')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True, max_length=300)),
                ('android', models.URLField(blank=True, max_length=300)),
                ('ios', models.URLField(blank=True, max_length=300)),
                ('web', models.URLField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('related_projects', models.CharField(max_length=400)),
                ('logo', models.ImageField(blank=True, upload_to='posts/skills')),
                ('term', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='portfolio.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
