# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='cover_photo',
            field=models.ImageField(upload_to='posts/hacks'),
        ),
    ]
